export const StarColorTop = {
  product: {
    cacheId: 'star-color-top',
    productName: 'Top Star Color Shirt',
    productId: '2000024',
    description: 'Colorful star on a tank top',
    titleTag: 'Star Color Top',
    metaTagDescription: 'Colorful star on a tank top',
    linkText: 'star-color-top',
    productReference: '998765',
    categoryId: '48',
    categories: [
      '/Apparel & Accessories/Clothing/Tops/',
      '/Apparel & Accessories/Clothing/',
      '/Apparel & Accessories/',
    ],
    brand: 'Kawasaki',
    brandId: 2000001,
    properties: [
      {
        name: 'On Sale',
        values: ['True'],
        __typename: 'Property',
      },
      {
        name: 'Sleeve type',
        values: ['Sleeveless'],
        __typename: 'Property',
      },
    ],
    specificationGroups: [
      {
        name: 'Group',
        specifications: [
          {
            name: 'On Sale',
            values: ['True'],
            __typename: 'SpecificationGroupProperty',
          },
        ],
        __typename: 'SpecificationGroup',
      },
      {
        name: 'Specifications',
        specifications: [
          {
            name: 'Sleeve type',
            values: ['Sleeveless'],
            __typename: 'SpecificationGroupProperty',
          },
        ],
        __typename: 'SpecificationGroup',
      },
      {
        name: 'allSpecifications',
        specifications: [
          {
            name: 'On Sale',
            values: ['True'],
            __typename: 'SpecificationGroupProperty',
          },
          {
            name: 'Sleeve type',
            values: ['Sleeveless'],
            __typename: 'SpecificationGroupProperty',
          },
        ],
        __typename: 'SpecificationGroup',
      },
    ],
    items: [
      {
        itemId: '2000564',
        name: 'Red star',
        nameComplete: 'Top Star Color Shirt Red star',
        complementName: 'Tank top with star',
        ean: '123456',
        referenceId: [
          {
            Key: 'RefId',
            Value: '987134',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155518',
            imageLabel: 'red',
            imageTag:
              '<img src="~/arquivos/ids/155518-#width#-#height#/download--40-.png?v=636942495289870000" width="#width#" height="#height#" alt="red" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155518/download--40-.png?v=636942495289870000',
            imageText: 'red',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000564&qty=1&seller=1&sc=1&price=3500&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 35,
              ListPrice: 35,
              PriceWithoutDiscount: 35,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['Red'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [
          {
            id: '13',
            name: 'Customization',
            required: false,
            __typename: 'Attachment',
          },
        ],
        __typename: 'SKU',
      },
      {
        itemId: '2000565',
        name: 'Magento',
        nameComplete: 'Top Star Color Shirt Magento',
        complementName: 'Tank top with star',
        ean: '123456',
        referenceId: [
          {
            Key: 'RefId',
            Value: '66678',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155519',
            imageLabel: 'magenta',
            imageTag:
              '<img src="~/arquivos/ids/155519-#width#-#height#/download--51-.png?v=636942496232070000" width="#width#" height="#height#" alt="magenta" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155519/download--51-.png?v=636942496232070000',
            imageText: 'magenta',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000565&qty=1&seller=1&sc=1&price=8740&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 87.4,
              ListPrice: 87.4,
              PriceWithoutDiscount: 87.4,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 21.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 21.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000567',
        name: 'Light blue',
        nameComplete: 'Top Star Color Shirt Light blue',
        complementName: 'Tank top with star',
        ean: '567567',
        referenceId: [
          {
            Key: 'RefId',
            Value: '9888',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155521',
            imageLabel: 'lightblue',
            imageTag:
              '<img src="~/arquivos/ids/155521-#width#-#height#/download--53-.png?v=636943145000300000" width="#width#" height="#height#" alt="light-blue" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155521/download--53-.png?v=636943145000300000',
            imageText: 'light-blue',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000567&qty=1&seller=1&sc=1&price=9240&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 92.4,
              ListPrice: 92.4,
              PriceWithoutDiscount: 92.4,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 46.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 18.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 15.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 46.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 18.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 15.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 46.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 92.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 92.4,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['Light blue'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000568',
        name: 'lilac',
        nameComplete: 'Top Star Color Shirt lilac',
        complementName: 'Tank top with star',
        ean: '',
        referenceId: [
          {
            Key: 'RefId',
            Value: '121299',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155522',
            imageLabel: 'lilac',
            imageTag:
              '<img src="~/arquivos/ids/155522-#width#-#height#/download--42-.png?v=636943145798400000" width="#width#" height="#height#" alt="lilac" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155522/download--42-.png?v=636943145798400000',
            imageText: 'lilac',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000568&qty=1&seller=1&sc=1&price=7020&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 70.2,
              ListPrice: 70.2,
              PriceWithoutDiscount: 70.2,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35.1,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 70.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 70.2,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000570',
        name: 'White',
        nameComplete: 'Top Star Color Shirt White',
        complementName: 'Tank top with star',
        ean: '4567878',
        referenceId: [
          {
            Key: 'RefId',
            Value: '0009',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155524',
            imageLabel: 'white',
            imageTag:
              '<img src="~/arquivos/ids/155524-#width#-#height#/download--43-.png?v=636943147443270000" width="#width#" height="#height#" alt="WHITE" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155524/download--43-.png?v=636943147443270000',
            imageText: 'WHITE',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000570&qty=1&seller=1&sc=1&price=3500&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 35,
              ListPrice: 35,
              PriceWithoutDiscount: 35,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 35,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 35,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['White'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [
          {
            id: '13',
            name: 'Customization',
            required: false,
            __typename: 'Attachment',
          },
        ],
        __typename: 'SKU',
      },
      {
        itemId: '2000571',
        name: 'Brown',
        nameComplete: 'Top Star Color Shirt Brown',
        complementName: 'Tank top with star',
        ean: '0890896',
        referenceId: [
          {
            Key: 'RefId',
            Value: '2002',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155525',
            imageLabel: 'brown',
            imageTag:
              '<img src="~/arquivos/ids/155525-#width#-#height#/download--48-.png?v=636943148698470000" width="#width#" height="#height#" alt="brown" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155525/download--48-.png?v=636943148698470000',
            imageText: 'brown',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000571&qty=1&seller=1&sc=1&price=5300&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 53,
              ListPrice: 53,
              PriceWithoutDiscount: 53,
              RewardValue: 1,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 26.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 13.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 10.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 26.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 13.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 10.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 26.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 53,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 53,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['Brown'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000572',
        name: 'grey',
        nameComplete: 'Top Star Color Shirt grey',
        complementName: 'Tank top with star',
        ean: '',
        referenceId: [
          {
            Key: 'RefId',
            Value: '8888888',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155526',
            imageLabel: 'grey',
            imageTag:
              '<img src="~/arquivos/ids/155526-#width#-#height#/download--44-.png?v=636943150013700000" width="#width#" height="#height#" alt="grey" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155526/download--44-.png?v=636943150013700000',
            imageText: 'grey',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000572&qty=1&seller=1&sc=1&price=8740&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 87.4,
              ListPrice: 87.4,
              PriceWithoutDiscount: 87.4,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 21.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 21.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000573',
        name: 'yellow',
        nameComplete: 'Top Star Color Shirt yellow',
        complementName: 'Tank top with star',
        ean: '',
        referenceId: [
          {
            Key: 'RefId',
            Value: '33242',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155527',
            imageLabel: 'yellow',
            imageTag:
              '<img src="~/arquivos/ids/155527-#width#-#height#/download--41-.png?v=636943151158800000" width="#width#" height="#height#" alt="yellow" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155527/download--41-.png?v=636943151158800000',
            imageText: 'yellow',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000573&qty=1&seller=1&sc=1&price=8740&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 87.4,
              ListPrice: 87.4,
              PriceWithoutDiscount: 87.4,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 21.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 21.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 17.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 14.6,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 43.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 87.4,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000574',
        name: 'Green',
        nameComplete: 'Top Star Color Shirt Green',
        complementName: 'Tank top with star',
        ean: '4234234',
        referenceId: [
          {
            Key: 'RefId',
            Value: '8300134',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155528',
            imageLabel: 'green',
            imageTag:
              '<img src="~/arquivos/ids/155528-#width#-#height#/download--46-.png?v=636943152112800000" width="#width#" height="#height#" alt="green" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155528/download--46-.png?v=636943152112800000',
            imageText: 'green',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000574&qty=1&seller=1&sc=1&price=4730&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 47.3,
              ListPrice: 47.3,
              PriceWithoutDiscount: 47.3,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 23.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 15.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 23.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 15.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 23.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 15.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 47.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 47.3,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['Green'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '2000577',
        name: 'orange',
        nameComplete: 'Top Star Color Shirt orange',
        complementName: 'Tank top with star',
        ean: '',
        referenceId: [
          {
            Key: 'RefId',
            Value: '49444',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155531',
            imageLabel: 'orange',
            imageTag:
              '<img src="~/arquivos/ids/155531-#width#-#height#/download--49-.png?v=636943154698270000" width="#width#" height="#height#" alt="orange" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155531/download--49-.png?v=636943154698270000',
            imageText: 'orange',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000577&qty=1&seller=1&sc=1&price=11930&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 119.3,
              ListPrice: 119.3,
              PriceWithoutDiscount: 119.3,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 59.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 39.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 19.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 59.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 39.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 29.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 23.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 19.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 59.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 39.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 119.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 119.3,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '310124162',
        name: 'Light Green',
        nameComplete: 'Top Star Color Shirt Light Green',
        complementName: 'Tank top with star',
        ean: '2342344',
        referenceId: [
          {
            Key: 'RefId',
            Value: '312322',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155588',
            imageLabel: 'Frente1',
            imageTag:
              '<img src="~/arquivos/ids/155588-#width#-#height#/Top-Star-Color-Shirt---Green.jpg?v=637088168561670000" width="#width#" height="#height#" alt="Frente" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155588/Top-Star-Color-Shirt---Green.jpg?v=637088168561670000',
            imageText: 'Frente',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=310124162&qty=1&seller=1&sc=1&price=3340&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 33.4,
              ListPrice: 33.4,
              PriceWithoutDiscount: 33.4,
              RewardValue: 1,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 16.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 16.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 16.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 11.2,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 33.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 33.4,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['Light green'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
      {
        itemId: '310124168',
        name: 'Rose',
        nameComplete: 'Top Star Color Shirt Rose',
        complementName: 'Tank top with star',
        ean: '098776541234',
        referenceId: null,
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155606',
            imageLabel: 'Frente1',
            imageTag:
              '<img src="~/arquivos/ids/155606-#width#-#height#/Top-Star-Color-Shirt---pink.jpg?v=637098714058400000" width="#width#" height="#height#" alt="Frente" id="" />',
            imageUrl:
              'https://storecomponents.vtexassets.com/arquivos/ids/155606/Top-Star-Color-Shirt---pink.jpg?v=637098714058400000',
            imageText: 'Frente',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=310124168&qty=1&seller=1&sc=1&price=3080&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 30.8,
              ListPrice: 30.8,
              PriceWithoutDiscount: 30.8,
              RewardValue: 0,
              PriceValidUntil: '2021-03-11T16:25:59Z',
              AvailableQuantity: 3000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                '3b1ceb60967ce6e49aa5f247fcd32ea7_',
              Installments: [
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 15.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 10.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 15.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 10.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 15.4,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 10.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 30.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 30.8,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Color',
            values: ['Rose'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        __typename: 'SKU',
      },
    ],
    skuSpecifications: [
      {
        field: {
          name: 'Color',
          __typename: 'SKUSpecificationField',
        },
        values: [
          {
            name: 'White',
            __typename: 'SKUSpecificationValue',
          },
          {
            name: 'Green',
            __typename: 'SKUSpecificationValue',
          },
          {
            name: 'Light green',
            __typename: 'SKUSpecificationValue',
          },
          {
            name: 'Light blue',
            __typename: 'SKUSpecificationValue',
          },
          {
            name: 'Brown',
            __typename: 'SKUSpecificationValue',
          },
          {
            name: 'Red',
            __typename: 'SKUSpecificationValue',
          },
          {
            name: 'Rose',
            __typename: 'SKUSpecificationValue',
          },
        ],
        __typename: 'SkuSpecification',
      },
    ],
    itemMetadata: {
      items: [
        {
          id: '2000564',
          name: 'Top Star Color Shirt Red star',
          imageUrl:
            'https://storecomponents.vtexassets.com/arquivos/ids/155518/download--40-.png?v=636942495289870000',
          seller: '1',
          assemblyOptions: [
            {
              id: 'Customization',
              name: 'Customization',
              required: false,
              inputValues: [
                {
                  label: 'Font',
                  maxLength: null,
                  type: 'OPTIONS',
                  domain: ['Sans serif', 'Roman'],
                  defaultValue: 'Sans serif',
                  __typename: 'InputValue',
                },
                {
                  label: 'Front text',
                  maxLength: 200,
                  type: 'TEXT',
                  domain: null,
                  defaultValue: '',
                  __typename: 'InputValue',
                },
                {
                  label: 'Back text',
                  maxLength: 200,
                  type: 'TEXT',
                  domain: null,
                  defaultValue: '',
                  __typename: 'InputValue',
                },
                {
                  label: 'Glossy print',
                  maxLength: null,
                  type: 'BOOLEAN',
                  domain: null,
                  defaultValue: true,
                  __typename: 'InputValue',
                },
              ],
              composition: null,
              __typename: 'AssemblyOption',
            },
          ],
          __typename: 'ItemMetadataUnit',
        },
        {
          id: '2000570',
          name: 'Top Star Color Shirt White',
          imageUrl:
            'https://storecomponents.vtexassets.com/arquivos/ids/155524/download--43-.png?v=636943147443270000',
          seller: '1',
          assemblyOptions: [
            {
              id: 'Customization',
              name: 'Customization',
              required: false,
              inputValues: [
                {
                  label: 'Font',
                  maxLength: null,
                  type: 'OPTIONS',
                  domain: ['Sans serif', 'Roman'],
                  defaultValue: 'Sans serif',
                  __typename: 'InputValue',
                },
                {
                  label: 'Front text',
                  maxLength: 200,
                  type: 'TEXT',
                  domain: null,
                  defaultValue: '',
                  __typename: 'InputValue',
                },
                {
                  label: 'Back text',
                  maxLength: 200,
                  type: 'TEXT',
                  domain: null,
                  defaultValue: '',
                  __typename: 'InputValue',
                },
                {
                  label: 'Glossy print',
                  maxLength: null,
                  type: 'BOOLEAN',
                  domain: null,
                  defaultValue: true,
                  __typename: 'InputValue',
                },
              ],
              composition: null,
              __typename: 'AssemblyOption',
            },
          ],
          __typename: 'ItemMetadataUnit',
        },
      ],
      priceTable: [],
      __typename: 'ItemMetadata',
    },
    productClusters: [
      {
        id: '1167',
        name: 'Coleção Black Friday',
        __typename: 'ProductClusters',
      },
      {
        id: '1170',
        name: 'Collection name',
        __typename: 'ProductClusters',
      },
      {
        id: '1171',
        name: 'Coleção xpto',
        __typename: 'ProductClusters',
      },
      {
        id: '1288',
        name: 'ola',
        __typename: 'ProductClusters',
      },
      {
        id: '1599',
        name: 'kkkkkkk',
        __typename: 'ProductClusters',
      },
    ],
    clusterHighlights: [],
    __typename: 'Product',
  },
  selectedItem: {
    itemId: '2000564',
    name: 'Red star',
    nameComplete: 'Top Star Color Shirt Red star',
    complementName: 'Tank top with star',
    ean: '123456',
    referenceId: [
      {
        Key: 'RefId',
        Value: '987134',
        __typename: 'Reference',
      },
    ],
    measurementUnit: 'un',
    unitMultiplier: 1,
    images: [
      {
        imageId: '155518',
        imageLabel: 'red',
        imageTag:
          '<img src="~/arquivos/ids/155518-#width#-#height#/download--40-.png?v=636942495289870000" width="#width#" height="#height#" alt="red" id="" />',
        imageUrl:
          'https://storecomponents.vtexassets.com/arquivos/ids/155518/download--40-.png?v=636942495289870000',
        imageText: 'red',
        __typename: 'Image',
      },
    ],
    videos: [],
    sellers: [
      {
        sellerId: '1',
        sellerName: 'VTEX',
        addToCartLink:
          'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000564&qty=1&seller=1&sc=1&price=3500&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
        sellerDefault: true,
        commertialOffer: {
          discountHighlights: [],
          teasers: [],
          Price: 35,
          ListPrice: 35,
          PriceWithoutDiscount: 35,
          RewardValue: 0,
          PriceValidUntil: '2021-03-11T16:25:59Z',
          AvailableQuantity: 3000000,
          Tax: 0,
          CacheVersionUsedToCallCheckout: '3b1ceb60967ce6e49aa5f247fcd32ea7_',
          Installments: [
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'American Express à vista',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Visa à vista',
              __typename: 'Installment',
            },
            {
              Value: 17.5,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 2,
              Name: 'Visa 2 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 11.7,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 3,
              Name: 'Visa 3 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Mastercard à vista',
              __typename: 'Installment',
            },
            {
              Value: 17.5,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 2,
              Name: 'Mastercard 2 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 11.7,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 3,
              Name: 'Mastercard 3 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Boleto Bancário à vista',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Promissory à vista',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Customer Credit à vista',
              __typename: 'Installment',
            },
            {
              Value: 17.5,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 2,
              Name: 'Customer Credit 2 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 11.7,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 3,
              Name: 'Customer Credit 3 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Free à vista',
              __typename: 'Installment',
            },
          ],
          __typename: 'Offer',
        },
        __typename: 'Seller',
      },
    ],
    variations: [
      {
        name: 'Color',
        values: ['Red'],
        __typename: 'Property',
      },
    ],
    kitItems: [],
    attachments: [
      {
        id: '13',
        name: 'Customization',
        required: false,
        __typename: 'Attachment',
      },
    ],
    __typename: 'SKU',
  },
  selectedQuantity: 1,
  skuSelector: {
    selectedImageVariationSKU: null,
    isVisible: false,
    areAllVariationsSelected: true,
  },
  buyButton: {
    clicked: false,
  },
  assemblyOptions: {
    items: {},
    inputValues: {},
    areGroupsValid: {},
  },
}

export const ProductOutOfStock = {
  ...StarColorTop,
  selectedItem: {
    ...StarColorTop.selectedItem,
    sellers: [
      {
        sellerId: '1',
        sellerName: 'VTEX',
        addToCartLink:
          'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000564&qty=1&seller=1&sc=1&price=3500&cv=3b1ceb60967ce6e49aa5f247fcd32ea7_&sc=1',
        sellerDefault: true,
        commertialOffer: {
          discountHighlights: [],
          teasers: [],
          Price: 35,
          ListPrice: 35,
          PriceWithoutDiscount: 35,
          RewardValue: 0,
          PriceValidUntil: '2021-03-11T16:25:59Z',
          AvailableQuantity: 0,
          Tax: 0,
          CacheVersionUsedToCallCheckout: '3b1ceb60967ce6e49aa5f247fcd32ea7_',
          Installments: [
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'American Express à vista',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Visa à vista',
              __typename: 'Installment',
            },
            {
              Value: 17.5,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 2,
              Name: 'Visa 2 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 11.7,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 3,
              Name: 'Visa 3 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Mastercard à vista',
              __typename: 'Installment',
            },
            {
              Value: 17.5,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 2,
              Name: 'Mastercard 2 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 11.7,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 3,
              Name: 'Mastercard 3 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Boleto Bancário à vista',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Promissory à vista',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Customer Credit à vista',
              __typename: 'Installment',
            },
            {
              Value: 17.5,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 2,
              Name: 'Customer Credit 2 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 11.7,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 3,
              Name: 'Customer Credit 3 vezes sem juros',
              __typename: 'Installment',
            },
            {
              Value: 35,
              InterestRate: 0,
              TotalValuePlusInterestRate: 35,
              NumberOfInstallments: 1,
              Name: 'Free à vista',
              __typename: 'Installment',
            },
          ],
          __typename: 'Offer',
        },
        __typename: 'Seller',
      },
    ],
  },
}

export const ProductWithInvalidAssemblies = {
  ...StarColorTop,
  assemblyOptions: {
    items: {},
    inputValues: {},
    areGroupsValid: {
      assemblyOne: false,
      assemblyTwo: true,
    },
  },
}
